#!/bin/zsh

CMAKEDONE=false

for i ($@) do
       case $i in
       Debug)   CMAKEDONE=true; cmake . -DBUILD_MODE=Debug              ;;
       Release) CMAKEDONE=true; cmake . -DBUILD_MODE=Release            ;;
       *)       echo "Unknown parameter \"${i}\""; exit                 ;;
       esac
done

if [ ! CMAKEDONE ]; then
	cmake .;
fi

make

exit 0
