#!/bin/zsh

for i ($@) do
       case $i in
       Debug)   cmake . -DBUILD_MODE=Debug              ;;
       Release) cmake . -DBUILD_MODE=Release            ;;
       *)       echo "Unknown parameter \"${i}\""; exit ;;
       esac
done

make

exit 0
