#!/bin/bash

find . -perm +100 -type f -delete

find . -name "Makefile" -type f -delete
find . -name "CMakeLists" -type d -delete
find . -name "*.cmake" -type f -delete
find . -name "*.a" -type f -delete

exit 0
