#!/bin/zsh

{
for i ($@) do
	case $i in
	--force)  rmeach Makefile                          ;;
	--noexec) rmexec                                   ;;
        *)        echo "Unknown parameter \"${i}\""; exit   ;;
	esac
done

rmeach CMakeFiles
rmeach *.cmake
rmeach CMakeCache.txt
rmeach Debug
rmeach Release
}&>/dev/null

exit
