#!/bin/zsh

if [ -f $1 ]; then 
	case $1 in
	*.tar.bz2)   tar xjf $1     ;;
	*.tar.gz)    tar xzf $1     ;;
	*.bz2)       bunzip2 $1     ;;
	*.rar)       unrar x $1     ;;
	*.gz)        gunzip $1      ;;
	*.tar)       tar xf $1      ;;
	*.tbz2)      tar xjf $1     ;;
	*.tbz)       tar -xjvf $1   ;;
	*.tgz)       tar xzf $1     ;;
	*.zip)       unzip $1       ;;
	*.Z)         uncompress $1  ;;
	*.7z)        7z x $1        ;;
	*)           echo "Error!\nCan't unpack '$1': unknown fmt!\n" ;;
	esac
else
	echo "Error!\n'$1' is not file!\n"	
fi

exit
